name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Version tag
        required: true

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    env:
      APP_NAME: nethermind-launcher
      PUB_DIR: artifacts
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Install npm packages
        run: npm i -g pkg @vercel/ncc
      - name: Build Nethermind launcher
        run: |
          mkdir -p \
            $PUB_DIR/linux-x64 \
            $PUB_DIR/linux-arm64 \
            $PUB_DIR/windows-x64 \
            $PUB_DIR/macos-x64 \
            $PUB_DIR/macos-arm64
          npm i
          pkg index.js -t latest-linux-x64 -o $PUB_DIR/$APP_NAME-linux-x64
          pkg index.js -t latest-win-x64 -o $PUB_DIR/$APP_NAME-windows-x64.exe
          pkg index.js -t latest-macos-x64 -o $PUB_DIR/$APP_NAME-macos-x64
          cp $PUB_DIR/$APP_NAME-macos-x64 $PUB_DIR/$APP_NAME-macos-arm64
      - name: Build Nethermind launcher for Linux arm64
        run: |
          docker buildx build --platform=linux/arm64 -t tmp-launcher --build-arg APP_NAME=$APP_NAME-linux-arm64 -f Dockerfile.arm64 . --load
          docker run --platform=linux/arm64 -v $PWD:/opt/mount --rm tmp-launcher bash -c "cp /nethermind/$APP_NAME-linux-arm64 /opt/mount/"
          mv $APP_NAME-linux-arm64 $PUB_DIR/
      - name: Publish to GitHub Releases
        env:
          GH_TOKEN: ${{ secrets.REPOSITORY_DISPATCH_TOKEN }}
        run: |
          gh release create ${{ github.event.inputs.tag }} -d --generate-notes --latest -t "${{ github.event.inputs.tag }}"
          gh release upload ${{ github.event.inputs.tag }} \
            $PUB_DIR/$APP_NAME-linux-x64 \
            $PUB_DIR/$APP_NAME-linux-arm64 \
            $PUB_DIR/$APP_NAME-windows-x64.exe \
            $PUB_DIR/$APP_NAME-macos-x64 \
            $PUB_DIR/$APP_NAME-macos-arm64
