name: Release

on:
  push:
    branches:
      - test/workflow
  workflow_dispatch:
    inputs:
      tag:
        description: Version tag
        required: true

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    env:
      APP_NAME: nethermind-launcher
      PUB_DIR: artifacts
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Publish to GitHub Releases
        env:
          GH_TOKEN: ${{ secrets.REPOSITORY_DISPATCH_TOKEN }}
        run: |
          echo "test" >> test.txt
          head_branch=feature/auto-update-${{ github.run_number }}-${{ github.run_attempt }}
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout -b $head_branch
          git add -A
          git commit -am "Auto-update docs"
          git push origin $head_branch
          gh pr create -B main -H $head_branch -t "test pr" -b "test pr"
